[GLOBAL]
# Root global config avaliable
# extension_directory = "extension"
# intent_type = "default"
# intent_flag = { "message" = true }

[DEVELOPMENT]
# Path to the extension directory.
extension_directory = "extension"
test_guilds = []

[PRODUCTION]
extension_directory = "extension"
