[GLOBAL]
# Root global config avaliable
# extension_directory = "extension"

[DEVELOPMENT]
# Path to the extension directory.
extension_directory = "extension"
test_guilds = []

[PRODUCTION]
extension_directory = "extension"
